[System]
Terminal=foot
Archiver=ark
SIUnit=true

[Behavior]
BookmarkOpenMethod=0
UseTrash=true
SingleClick=false
ConfirmDelete=true

[Volume]
MountOnStartup=false
MountRemovable=false
AutoRun=false

[FolderView]
Mode=list
ShowHidden=false
SortOrder=ascending
SortColumn=name
BigIconSize=48
SmallIconSize=24
SidePaneIconSize=24
ThumbnailIconSize=128

[Window]
RememberWindowSize=true
AlwaysShowTabs=false
ShowTabClose=true
SplitterPos=250

[Thumbnail]
ShowThumbnails=true
MaxThumbnailFileSize=4096
ThumbnailLocalFilesOnly=true
